services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: STRIPE_WEBHOOK_SECRET
        fromEnvVar: STRIPE_WEBHOOK_SECRET
      - key: SQL_KEY
        fromEnvVar: SQL_KEY
      - key: REDIS_BROKER_URL
        fromEnvVar: REDIS_BROKER_URL

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.worker.celery_app worker --loglevel=info --pool=threads --concurrency=4
